#####################################################
################# Spring properties #################
#####################################################
spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5438}/${DB_NAME:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      minimumIdle: 2
      idleTimeout: 120000
      maxLifetime: 900000
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/liquibase-changelog.xml
  main:
    allow-bean-definition-overriding: true

#####################################################
################# Server properties #################
#####################################################
server:
  port: 8080
  servlet:
    context-path: /api/v1
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  shutdown: graceful

#####################################################
################ Swagger properties #################
#####################################################
swagger:
  enabled: ${SWAGGER_ENABLED:true}
